### ISSUE TITLE
Builds for Python 3.10

### ISSUE THREAD

**Issue by hriebl** [cloudhan/jax-windows-builder#1]
Thank you very much for your work! Are you planning to provide builds for Python 3.10 anytime soon?

**Comment by cloudhan** [comment]
I am not sure about it. The upper limit of github actions is 6 hours, adding a new python generally requires additional 5 to 10 minutes after a full build from scratch. Currently the  CI is reaching the limit.

**Comment by hriebl** [comment]
I see, thank you! Guess we'll need to wait until 3.10 becomes popular enough to replace 3.7 on the build list then... :slightly_smiling_face:

**Comment by cloudhan** [comment]
@hriebl I managed added python 3.10 build, see https://github.com/cloudhan/jax-windows-builder/actions/runs/1850816129

The slow build time metioned above is due to some github CI machines' CPU are Xeon E5 model, which is pretty old... So I added some simple logic to avoid those machines.

**Comment by hriebl** [comment]
Amazing! Thank you very much!
