### ISSUE TITLE
TF Compression and TensorFlow Federated 

### ISSUE THREAD

**Issue by madhavajay** [cloudhan/jax-windows-builder#17]
Now that these jaxlib wheels exist, the only compiled dependency for windows that prevents TFF from running is `tensorflow-compression`.

https://github.com/tensorflow/compression

If we can get the requirements for jax and jaxlib relaxed a little bit here:
https://github.com/tensorflow/federated/pull/3242

I imagine TF compression is no where as complicated as jaxlib + cuda etc to get running in a fork and provide wheels.

Is this something you would be interested in some help with?

**Comment by cloudhan** [comment]
Sorry, not at the moment. Although it seems to be straightforward to maintain native builds when it builds, but it involves convoluted debugging process if errors happen.

**Comment by madhavajay** [comment]
@cloudhan okay no worries, maybe ill take a stab at it.
Any plans on a 0.3.17 release?

**Comment by cloudhan** [comment]
Added 0.3.17, see https://github.com/cloudhan/jax-windows-builder/actions/runs/3098881843

Note, that the jaxlib version ∈ (0.3.14, 0.3.17) is not buildable due to upstraem tf problem.

Close for now.
