### ISSUE TITLE
XLA fails not finding DNN, even though only using the CPU-only build

### ISSUE THREAD

**Issue by EgorKraevTransferwise** [cloudhan/jax-windows-builder#18]
HI! Thanks a lot for providing these builds!

I've installed jax on my Windows 10 via ` pip install "jax[cpu]===0.3.14" -f https://whls.blob.core.windows.net/unstable/index.html --use-deprecated legacy-resolver` and then lightweightMMM via `pip install lightweight_mmm`. Then when I try to run the [simple example notebook](https://github.com/google/lightweight_mmm/blob/main/examples/simple_end_to_end_demo.ipynb), the `utils.simulate_dummy_data()` call fails because XLA can't find DNN. 

Why would this be an issue, if I'm running a CPU-only build?

Many thanks for any hints you can give,
E.

```
XlaRuntimeError: UNKNOWN: Failed to determine best cudnn convolution algorithm for:
%cudnn-conv = (f32[1,3,140]{2,1,0}, u8[0]{0}) custom-call(f32[1,3,140]{2,1,0} %bitcast.1, f32[3,1,25]{2,1,0} %bitcast.2), window={size=25 pad=12_12}, dim_labels=bf0_oi0->bf0, feature_group_count=3, custom_call_target="__cudnn$convForward", metadata={op_name="jit(carryover)/jit(main)/conv_general_dilated[window_strides=(1,) padding=((12, 12),) lhs_dilation=(1,) rhs_dilation=(1,) dimension_numbers=ConvDimensionNumbers(lhs_spec=(0, 1, 2), rhs_spec=(0, 1, 2), out_spec=(0, 1, 2)) feature_group_count=3 batch_group_count=1 lhs_shape=(1, 3, 140) rhs_shape=(3, 1, 25) precision=None preferred_element_type=None]" source_file="C:\\Users\\egor.kraev\\.conda\\envs\\py38_jax\\lib\\site-packages\\lightweight_mmm\\media_transforms.py" source_line=133}, backend_config="{\"conv_result_scale\":1,\"activation_mode\":\"0\",\"side_input_scale\":0}"

Original error: UNIMPLEMENTED: DNN library is not found.
```

**Comment by cloudhan** [comment]
See https://github.com/cloudhan/jax-windows-builder/issues/9
