### ISSUE TITLE
CUDA versions of Jaxlib 0.3.x?

### ISSUE THREAD

**Issue by adam-hartshorne** [cloudhan/jax-windows-builder#2]
There doesn't seem to be any CUDA versions of jaxlib 0.3.x. 

Looking at your Github "actions", it looks like the build failed, with some complaints about lack of disk space.

**Comment by cloudhan** [comment]
Yes, that is the case, just don't have time to dig into it now.

**Comment by cloudhan** [comment]
https://github.com/cloudhan/jax-windows-builder/actions/runs/1923639612
