### ISSUE TITLE
Python 3.11

### ISSUE THREAD

**Issue by madhavajay** [cloudhan/jax-windows-builder#22]
The main repo is doing 3.11 releases now so it would be awesome to get some 3.11 releases possibly even for some retrospective versions as well.

**Comment by cloudhan** [comment]
jaxlib 0.4.1 is not buildable due to https://github.com/google/jax/issues/13871, so this repo hasn't been updated for a while.

**Comment by adam-hartshorne** [comment]
jaxlib 0.4.2 is now out.

**Comment by cloudhan** [comment]
0.4.2 is not buildable due to https://github.com/google/jax/issues/14165 either :(. I currectly do not have time to fix these type of errors and upstream the patch. Let's hope someone will work on it.

**Comment by adam-hartshorne** [comment]
It seems quite a few build issues come from the fact that MSVC always has its own (often off standard) quirks and the various teams involved with JAX / TF / XLA never use MSVC. Is there any reason not to just build via LLVM compilation (as its available for Windows)?

**Comment by cloudhan** [comment]
If TF is buildable with clang on windows, then it will actually be possible.

**Comment by madhavajay** [comment]
@cloudhan thank you so much for the cp11 cpu builds.
https://github.com/OpenMined/PySyft/pull/7683
