### ISSUE TITLE
Fixing Build Question From #14466 Post

### ISSUE THREAD

**Issue by adam-hartshorne** [cloudhan/jax-windows-builder#23]
I have been working through your excellent post https://github.com/google/jax/issues/14466 , and got to this part.

> Cause of already defined xla::runtime::ffi::GetXlaFfiStream xla::runtime::ffi::GetXlaFfiStream is first defined as weak symbol in ffi.cc
> then defined as normal symbol in executable.cc and msvc does not support weak symbol.
> 
> As for dirty fix, removing the definition in ffi.cc and replacing it with decl will allow the linking to pass. 

I understand the weak symbol issue, but could you clarify what exactly what changes you made when you state by "replace it with a decl".

**Comment by cloudhan** [comment]
Just comment out the function body.
```cpp
int func() {}
// to 
int func();
```

**Comment by adam-hartshorne** [comment]
That's what I thought, but I was still getting an error. 

Edit - A clean rebuild sorted out the issue. Thanks
