### ISSUE TITLE
CPU only builds?

### ISSUE THREAD

**Issue by madhavajay** [cloudhan/jax-windows-builder#25]
Any chance you could add CPU only builds from this PR:
https://github.com/google/jax/pull/15009

That would at least allow many jax dependent libraries from providing support (e.g. clients and inference etc) even if its slow.

**Comment by cloudhan** [comment]
There is cpu build now in this repo. I'm not quite get what the "**add**" means here. If you are aiming at merge the mentioned PR into google/jax, then I am afraid I can not give a help, as I am not affiliated with Google Inc.

The problem is starting from 0.4.0, all of them are breaking due to upstream changes. I am aiming at fixing them all

**Comment by madhavajay** [comment]
@cloudhan sorry, I was under the impression that the Github CI task in the above PR which targets Windows x64 supports 3.11 which would provide 3.11 here as well. Is python 3.11 for CPU blocked by another reason such as what you mentioned in this issue: https://github.com/cloudhan/jax-windows-builder/issues/22

I am happy to investigate the fixes if you can point me in the right direction.
Do I just need to add some cp11 stuff to the CPU tasks:
https://github.com/cloudhan/jax-windows-builder/blob/f0a5e2008bfc9842d30c8e7af0aa75a0f912ed0b/.github/workflows/ci-build.yml#L11

Both python 3.11 and newer jax builds are desirable but I will take either if we can't have both.

**Comment by cloudhan** [comment]
I think it should be buildable now? Most of the issue is caused by CUDA. I might trigger one this weekend.

**Comment by madhavajay** [comment]
@cloudhan that would be super duper awesome. ❤️❤️❤️❤️

**Comment by cloudhan** [comment]
Close for now. 0.4.9 and 0.4.10 cpu whls are added.

**Comment by madhavajay** [comment]
Working beautifully: https://github.com/OpenMined/PySyft/pull/7683
