### ISSUE TITLE
 jaxlib-v0.3.2 Unreleased - Does you system automatically rebuild when re-released?

### ISSUE THREAD

**Issue by adam-hartshorne** [cloudhan/jax-windows-builder#4]
I notice jaxlib-v0.3.2. has been unreleased for some reason. I was wondering does the way you have the github actions setup result in a new version being rebuilt when v0.3.2. is re-released?

**Comment by cloudhan** [comment]
Might be your browser or some other cache mechanism that is retrieving old version index.html for you. Try https://whls.z5.web.core.windows.net/unstable/index.html this is the static website url.

**Comment by adam-hartshorne** [comment]
Sorry to clarify. I mean on the Jax Github, https://github.com/google/jax/releases, v0.3.2. has been withdrawn. And on the commits, there is Update WORKSPACE for jaxlib 0.3.2, take 2
 (https://github.com/google/jax/commit/1ba51786c01b1348b9c68d0c1ae48fc1366e21ba)

I am asking, when jaxlib 0.3.2, take 2 is actually released, does your github actions automatically rebuild this re-released version?

**Comment by cloudhan** [comment]
Nope. There is no automatic submodule update. Their release cycle is pretty slow, so I manually update it now.

**Comment by cloudhan** [comment]
But if a new build is triggered with existing version, the old one will be overwrited.
