### ISSUE TITLE
WARNING: jax 0.3.4 does not provide the extra 'cuda111'

### ISSUE THREAD

**Issue by illtellyoulater** [cloudhan/jax-windows-builder#5]
Hello, I'm running the following command as described in your README

`pip install jax[cuda111] -f https://whls.blob.core.windows.net/unstable/index.html --use-deprecated legacy-resolver`

but I get a warning saying that jax does not provide the extra 'cuda111'

Full command output:

```
Looking in links: https://whls.blob.core.windows.net/unstable/index.html
Processing c:\users\myname\appdata\local\pip\cache\wheels\09\88\75\b38c1c9382c2a6e9d3ab993f7b\jax-0.3.4-py3-none-any.whl
  WARNING: jax 0.3.4 does not provide the extra 'cuda111'
Requirement already satisfied: absl-py in ... (from jax[cuda111]) (1.0.0)
Requirement already satisfied: numpy>=1.19 in ... (from jax[cuda111]) (1.21.5)
Requirement already satisfied: typing-extensions in ... (from jax[cuda111]) (4.1.1)
Requirement already satisfied: scipy>=1.2.1 in ... (from jax[cuda111]) (1.8.0)
Requirement already satisfied: opt-einsum in ... (from jax[cuda111]) (3.3.0)
Requirement already satisfied: six in ... (from absl-py->jax[cuda111]) (1.16.0)
Installing collected packages: jax
Successfully installed jax-0.3.4
```

Am I doing something wrong?

**Comment by cloudhan** [comment]
See https://github.com/google/jax/blob/f47ce791da7ef522405fdda189d7ace827530573/setup.py#L71-L75

Currently the file name is not standard for the new versions. You need to install the jaxlib manually. Just follow https://github.com/cloudhan/jax-windows-builder#the-ultimate-solution
