### ISSUE TITLE
Q: Installing CPU only version

### ISSUE THREAD

**Issue by rasswanth-s** [cloudhan/jax-windows-builder#9]
@cloudhan , 
Really Great work on the jax windows builder,

While Installing jaxlib using:
pip install jaxlib -f https://whls.blob.core.windows.net/unstable/index.html --use-deprecated legacy-resolver

This always the install the cuda version (https://whls.blob.core.windows.net/unstable/cuda111/jaxlib-0.3.5+cuda11.cudnn82-cp39-none-win_amd64.whl)

How do I make it install only the CPU version without direct link usage like
pip install https://whls.blob.core.windows.net/unstable/cpu/jaxlib-0.3.5-cp39-none-win_amd64.whl

**Comment by cloudhan** [comment]
If you add `-v -v -v` to the command line, you will see both cpu and cuda version are matched, however pip still choose to install cuda version in this case. I am guessing that I need to provide index.html for cpu and cuda seperately.... :(

**Comment by cloudhan** [comment]
`pip install jaxlib===0.3.5 -f https://whls.blob.core.windows.net/unstable/index.html` will do the trick. https://togithub.com/pypa/pip/issues/6333 is a similar issue. See https://peps.python.org/pep-0440/#arbitrary-equality, but `pip install jax[cpu]` will need a patch toward jax.

**Comment by rasswanth-s** [comment]
@cloudhan , Thanks for the quick reply, I noticed, in pytorch, they name their CPU version with pytorch_1.1.0+cpu,
so we could install like pip instal torch==1.10.0+cpu
